{% set name = "quixstreams" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quixio/quix-streams/archive/v{{ version }}.tar.gz
  sha256: 16a49ca309ea562fedc1136217cd83cfa4433612cac1826d816b3f38e98ef487

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4
    - setuptools
    - pip
  run:
    - python >=3.9,<4
    - python-confluent-kafka >=2.2,<2.5
    - requests >=2.32
    - rocksdict >=0.3,<0.4
    - typing_extensions >=4.8
    - orjson >=3.9,<4
    - pydantic >=2.7,<2.10
    - pydantic-settings >=2.3,<2.6
    - jsonschema >=4.3.0

test:
  imports:
    - quixstreams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quixio/quix-streams
  doc_url: https://docs.quix.io/
  summary: Python library for building stream processing applications with Apache Kafka
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
