{% set name = "quixstreams" %}
{% set version = "3.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quixio/quix-streams/archive/v{{ version }}.tar.gz
  sha256: be7890366997e26cd06be9bbdd16f75c779f6617691c5ded2e28555be9c236ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - python-confluent-kafka >=2.8.2,<2.12
    - rocksdict >=0.3,<0.4
    - typing_extensions >=4.8
    - orjson >=3.9,<4
    - pydantic >=2.7,<2.14
    - pydantic-settings >=2.3,<2.12
    # Superceded below
    # - jsonschema >=4.3.0
    - jsonlines >=4,<5
    - rich >=13,<15
    - jsonpath-ng >=1.7.0,<2
    - httpx >=0.28.1
    # From confluent-kafka-avro
    - fastavro >=1.5.4,<2
    - requests
    - avro >=1.11.1,<2
    # From conflient-kafka-json
    - jsonschema >=4.18.0
    # From conflient-kafka-protobuf
    - googleapis-common-protos
    - protobuf
    # From conflient-kafka-schemaregistry
    - attrs >=21.2.0
    - cachetools >=5.5.0
    - certifi
    - httpx2 >=2.0
    - authlib >=1.8.0

test:
  imports:
    - quixstreams
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quixio/quix-streams
  doc_url: https://docs.quix.io/
  summary: Python library for building stream processing applications with Apache Kafka
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
