{% set name = "quixstreams" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quixio/quix-streams/archive/v{{ version }}.tar.gz
  sha256: 265da11c825bee1d014c3231c446a23f7db238a33a2a8d80b806eeeeab50d93a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - python-confluent-kafka >=2.8.2,<2.9
    - requests >=2.32
    - rocksdict >=0.3,<0.4
    - typing_extensions >=4.8
    - orjson >=3.9,<4
    - pydantic >=2.7,<2.11
    - pydantic-settings >=2.3,<2.7
    - jsonschema >=4.3.0
    - jsonlines >=4,<5
    - rich >=13,<14
    # for confluent-kafka[avro,json,protobuf,schemaregistry]
    - fastavro <2
    - avro >=1.11.1,<2
    - pyrsistent
    - googleapis-common-protos
    - protobuf
    - attrs
    - cachetools
    - httpx >=0.26
    - authlib

test:
  imports:
    - quixstreams
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quixio/quix-streams
  doc_url: https://docs.quix.io/
  summary: Python library for building stream processing applications with Apache Kafka
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
